// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFI_5nozuTI-hjMuLBGVwDj-Co296ryQs',
    appId: '1:536678879857:web:b3722261bfceb7edfc41d0',
    messagingSenderId: '536678879857',
    projectId: 'nvisust-c0883',
    authDomain: 'nvisust-c0883.firebaseapp.com',
    storageBucket: 'nvisust-c0883.firebasestorage.app',
    measurementId: 'G-ESFNX5107K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjsbEMqZGYR47gqsqMDZXgilPOWqezdbs',
    appId: '1:536678879857:android:4efaea31ae400d62fc41d0',
    messagingSenderId: '536678879857',
    projectId: 'nvisust-c0883',
    storageBucket: 'nvisust-c0883.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtsTN393uVKT9CC9kcDk4-Zna8mK8fWvg',
    appId: '1:536678879857:ios:4fa3e59c34447b4cfc41d0',
    messagingSenderId: '536678879857',
    projectId: 'nvisust-c0883',
    storageBucket: 'nvisust-c0883.firebasestorage.app',
    iosBundleId: 'com.example.nvisustTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtsTN393uVKT9CC9kcDk4-Zna8mK8fWvg',
    appId: '1:536678879857:ios:4fa3e59c34447b4cfc41d0',
    messagingSenderId: '536678879857',
    projectId: 'nvisust-c0883',
    storageBucket: 'nvisust-c0883.firebasestorage.app',
    iosBundleId: 'com.example.nvisustTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFI_5nozuTI-hjMuLBGVwDj-Co296ryQs',
    appId: '1:536678879857:web:82a91d8231e8b696fc41d0',
    messagingSenderId: '536678879857',
    projectId: 'nvisust-c0883',
    authDomain: 'nvisust-c0883.firebaseapp.com',
    storageBucket: 'nvisust-c0883.firebasestorage.app',
    measurementId: 'G-3X9Y76NQ9R',
  );
}
